# Generated by Django 4.2.5 on 2024-03-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('eid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
