# Generated by Django 4.2.10 on 2024-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
