# Generated by Django 4.2.1 on 2024-03-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "urollno",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("uname", models.CharField(max_length=100)),
                ("uemail", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=1)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject1", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=10)),
                (
                    "users_uid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "mark",
            },
        ),
    ]
