# Generated by Django 4.2.1 on 2024-03-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.AddField(
            model_name="users",
            name="ucontact",
            field=models.CharField(default=9876543210, max_length=10),
            preserve_default=False,
        ),
    ]
